# A list of members able to review PRs (github users)
teamMembers:
  - guidota
  - martincousido
  - guidota2

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip
